### PR TITLE
Add Google OAuth

### PR DESCRIPTION
**Pull request by R2bEEaton**
Took a while, but I finally got OAuth to work. There are still some things we should add like caching the user's profile picture and stuff, but this is a good barebones start! You can use "isAuthenticated" like in the Redwood tutorials. I also added some instructions in the readme for how to get the Client ID and Secret from our Google Cloud project. Testing would be really helpful for this, just in case I missed something in the tutorial I wrote.

### CODE REVIEW

**Comment by R2bEEaton** [comment]
I still need to figure out how to test the API side

**Comment by R2bEEaton** [comment]
Sheesh finally got the API tests to work with Postgres

**Review by jswitlyk — APPROVED** [review]
Everything is working on my end.

**Comment by jswitlyk** [comment]
I tested again with the new changes. Everything looks good.

**Pull request merged**
